### PR TITLE
12 create a login with GitHub option

### LINKED ISSUE #12: Create a login with Github option
Currently, there are options for Facebook and Google login options.

Unless we want to keep one of these two options, we will need to replace the two with one option to log in with Github.

### PR DESCRIPTION
**Pull request by Ejemy**
## Issues
closes #12

## Description
Adds the feature to login with a GitHub account.
While this works I think I have some doubts so please look over carefully! Because it is logging in with github it does not use bcrypt as I don't think it's needed. Please correct me if I'm wrong.

## Proposed Changes
  Add a new passport authentication which uses passport-github2 package. This will use OAuth package to validate through Github. The ENV files for the github authentication are hidden inside of .dev.env file so they do not get deleted. I have created the Oauth process but handed off ownership to RJD27 (awaiting on that still).

### CODE REVIEW

**Comment by TheHungryBandito** [comment]
When I register with GitHub I get this error, however, I do also get an email saying the application has been added to my account. Is this expected so far?

```commandline
TypeError: Cannot read properties of undefined (reading '0')
    at Strategy._verify (C:\GitHub\Ticketing_System\startbootstrap-sb-admin-2-gh-pages\js\auth.js:49:48)
    at C:\GitHub\Ticketing_System\startbootstrap-sb-admin-2-gh-pages\node_modules\passport-oauth2\lib\strategy.js:205:24
    at C:\GitHub\Ticketing_System\startbootstrap-sb-admin-2-gh-pages\node_modules\passport-github2\lib\strategy.js:123:14
    at passBackControl (C:\GitHub\Ticketing_System\startbootstrap-sb-admin-2-gh-pages\node_modules\oauth\lib\oauth2.js:134:9)
    at IncomingMessage.<anonymous> (C:\GitHub\Ticketing_System\startbootstrap-sb-admin-2-gh-pages\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by Ejemy** [comment]
> When I register with GitHub I get this error, however, I do also get an email saying the application has been added to my account. Is this expected so far?
> 
> ```
> TypeError: Cannot read properties of undefined (reading '0')
>     at Strategy._verify (C:\GitHub\Ticketing_System\startbootstrap-sb-admin-2-gh-pages\js\auth.js:49:48)
>     at C:\GitHub\Ticketing_System\startbootstrap-sb-admin-2-gh-pages\node_modules\passport-oauth2\lib\strategy.js:205:24
>     at C:\GitHub\Ticketing_System\startbootstrap-sb-admin-2-gh-pages\node_modules\passport-github2\lib\strategy.js:123:14
>     at passBackControl (C:\GitHub\Ticketing_System\startbootstrap-sb-admin-2-gh-pages\node_modules\oauth\lib\oauth2.js:134:9)
>     at IncomingMessage.<anonymous> (C:\GitHub\Ticketing_System\startbootstrap-sb-admin-2-gh-pages\node_modules\oauth\lib\oauth2.js:157:7)
>     at IncomingMessage.emit (node:events:525:35)
>     at endReadableNT (node:internal/streams/readable:1359:12)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> ```

That's interesting.... I believe that is referencing the github Strategy here..
```
 AddUserToDatabase(
              connection,
              profile.username,
              profile.username,
              profile.emails[0].value
            )
```
I thought I had done some console logs for profile.emails[0] and got no errors. That's strange. You could try consoling profile.emails and seeing what you get?

**Comment by Ejemy** [comment]
@TheHungryBandito I guess if it worked that's fine? Could you check your DB and see if the github account got added? I'm currently away and can't do this myself. Will try tonight too.

**Comment by TheHungryBandito** [comment]
@Ejemy I have discovered after some logging and testing that a check needs to be implemented that checks if the profile has any public emails.

The cause of my problem was that on my GitHub account, I had my email set to private, therefore, when accessing my profile's emails it would return null.

Recommended Fix: Implement a check at around line 48:auth.js that returns an error (preferably that could be displayed to the user to let them know they don't have public emails set).

This added code is untested but I imagine the check would be something like so:

```javascript
// auth.js
passport.use("github",
      new GitHubStrategy({
        //don't want to lose this when pushing so maybe in official app we can put this in ENV?
        clientID: process.env.CLIENT_ID,
        clientSecret: process.env.CLIENT_SECRET,
        callbackURL: "http://localhost:3000/auth/github/callback"
      }, 
      function(accessToken, refreshToken, profile, cb){
        // Added emails check.
        if (profile.emails < 1)
        {
          return console.log("There are no public emails on this account");
        }
        var check = "SELECT 1 FROM users WHERE Email = ?";
        console.log(profile);
        connection.query(check, [profile.emails[0].value], function(err, user){
        console.log("connection query for git")

          if(err){
            return console.log(err);
          }
          // ... rest of the code
```

Side Problem: In the database, it puts your GitHub username in both first name and last name positions meaning your name will be <Username> <Username>. I have noticed you can access the user's name using profile.name which gives you a full name, this could be split and added instead perhaps?

**Comment by Ejemy** [comment]
@TheHungryBandito  @RJD27 
Added the fix along with first last names

**Pull request merged**
