### PR TITLE
Login page backend

### LINKED ISSUE #4: Create Login Backend
We need a backend for our login page. It will need to authenticate the user using our database and log them into the website.

### LINKED ISSUE #7: Complete password encryption/decryption
Once the login backend is merged with main, password encryption should be updated to work with both registration and login.

### PR DESCRIPTION
**Pull request by Ejemy**
## Issues
closes #4

## Description
It can't automatically merge. I guess some things are incompatible. Help me out here.
Not sure if this will break the previous pull request but let me know any issues an I'll gladly work them out!
Sorry if this pull was done incorrectly. 

## Proposed Changes
  - Added login and passport authentication.

### CODE REVIEW

**Comment by TheHungryBandito** [comment]
Problem: I think the conflicts are to do with the structure of your local repository. 

Looking at the main branch I see that the website code is under a sub folder called 'startbootstrap-sb-admin-2-gh-pages', 
however on this branch the files seem to be out of the sub-folder.

Fix: Re-structure your local repo to reflect that of main and re-push.

**Comment by Ejemy** [comment]
I have reorganized the local repo and pushed again (I think).

**Comment by TheHungryBandito** [comment]
I am resolving the conflicts using Git Bash.

**Comment by TheHungryBandito** [comment]
I have resolved all conflicts and integrated bcrypt to login.
This PR should also now close #7

**Review by TheHungryBandito — APPROVED** [review]
Code looks good and works well, this should be safe to merge.
Also keep in mind the description section of the PR should include a description of what your code does/is.

**Pull request merged**
